### ISSUE TITLE
Laravel 6 Compatibility

### ISSUE THREAD

**Issue by DerekBuntin** [InfinetyES/Nova-Menu-Builder#13]
I've just upgraded to Laravel 6 and experiencing issues with the menu builder that references old methods, any updates when Laravel 6 will be supported?

`Call to undefined function Infinety\MenuBuilder\Http\Models\starts_with()`

**Comment by KnowledgeWanderer** [comment]
any news @InfinetyEs there are many classes and functions that were deprecated and need to be updated in L6

**Comment by eugenpasca** [comment]
+1 on the issue

**Comment by atmonshi** [comment]
I create a PR #14  for this .

**Comment by Krato** [comment]
Merged. Thanks @atmonshi. Please update to v2
