### ISSUE TITLE
undefined function str_slug() in Laravel 6.0

### ISSUE THREAD

**Issue by pwronline** [InfinetyES/Nova-Menu-Builder#15]
String and Array helpers are removed from laravel 6.0 Core Framework

https://laravel.com/docs/6.0/upgrade#helpers

So if You need to still use the helper install the package

`composer require laravel/helpers`

Or you can use by Laravel facade

```
use Illuminate\Support\Str;
$slug = Str::slug('Laravel 5 Framework', '-');
```

**Comment by Manoz** [comment]
Nice catch. Here's the fix :p

**Comment by pwronline** [comment]
Thx! @Manoz good job!
