### ISSUE TITLE
Class "nav-link" in menu settings

### ISSUE THREAD

**Issue by sidorenkoda** [InfinetyES/Nova-Menu-Builder#2]
It is not good code:
`
/vendor/infinety-es/nova-menu-builder/src/Http/Models/MenuItems.php
return '<a class="nav-link '.$this->classes.'" href="'.$this->link.'" target="'.$this->target.'">'.$this->name.'</a>';
`
I propose to bring this parameter to this place - /nova/resources/menu-builder/1/edit
Do you need help?

**Comment by Krato** [comment]
Hello @sidorenkoda.

First, I removed the exclamation from the title. This isn't a place to shout.

Also, you say that isn't a good code. Maybe that depends of your code. 

But of course, you can send a PR, and we will approve it, or not.

Regards

**Comment by Krato** [comment]
Close due inactivity
