### ISSUE TITLE
Get menu name in blade files?

### ISSUE THREAD

**Issue by Manoz** [InfinetyES/Nova-Menu-Builder#3]
Is there a way to get the menu name in my blade views?
I'm not using Vue in my website front views so I can't properly use the json feature. 

Also I'm not sure about this but if I want to test if the menu exists I'll do something like this:
```
@if (menu_builder('main'))
    {!! menu_builder('main') !!}
@endif
```
But what if somehow I change the slug? I wonder if there's a better way to achieve this. 

Thx for your work anyways :)

**Comment by hofmannsven** [comment]
I think this could be a useful enhancement for the package.

As a quick solution you can create your own helper function to get the menu name:
```php
if (!function_exists('menu_name')) {
    function menu_name($slug)
    {
        $menu = Menu::whereSlug($slug)->first();
        if (!$menu) {
            return '';
        }

        return $menu->name;
    }
}
```

**Comment by Krato** [comment]
@hofmannsven maybe you can add a pull request. Thanks!
